# Generated by Django 4.0 on 2022-08-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='اسم السائق')),
                ('number_of_car', models.IntegerField(blank=True, null=True, verbose_name='رقم العربية')),
                ('date_of_get_in', models.DateField(blank=True, null=True, verbose_name='تاريخ الدخول')),
                ('date_of_get_out', models.DateField(blank=True, null=True, verbose_name='تاريخ الخروج')),
                ('load', models.TextField(blank=True, null=True, verbose_name='الحمولة')),
                ('added_data', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='اسم مدخل البيانات')),
            ],
            options={
                'verbose_name': 'بيانات الحمولة',
                'verbose_name_plural': 'بيانات الحمولة',
            },
        ),
    ]
