# Generated by Django 3.2.9 on 2022-08-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20220817_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaddata',
            name='edited_data',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='اسم القائم بالتعديل'),
        ),
        migrations.AlterField(
            model_name='loaddata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
